# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Frontend

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  workflow_run:
    workflows: [Test Frontend]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: MaldiSession

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - run: |
          yarn install
          yarn build
          yarn test
        working-directory: ./frontend

      - name: Copy files to s3
        run: |
          aws s3 sync ./dist s3://maldi.lfm.dev
        working-directory: ./frontend

      - name: Invalidate cloudfront distribution
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID}} \
          --paths "/*"
